force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Coordinates_Latitude__c.field-meta.xml
<CustomField>
    <fullName>Coordinates_Latitude__c</fullName>
    <label>Coordinates/Latitude</label>
    <precision>18</precision>
    <required>true</required>
    <scale>15</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Coordinates_Longitude__c.field-meta.xml
<CustomField>
    <fullName>Coordinates_Longitude__c</fullName>
    <label>Coordinates/Longitude</label>
    <precision>18</precision>
    <required>true</required>
    <scale>15</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>District</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Handover__c.field-meta.xml
<CustomField>
    <fullName>Handover__c</fullName>
    <label>Handover</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Minimum_Cost__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Cost__c</fullName>
    <inlineHelpText>Will be calculated automatically according to all related &apos;Published&apos; Units, after you change their Status or Cost</inlineHelpText>
    <label>Minimum Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/District.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Discovery Gardens</fullName>
        <default>true</default>
        <label>Al Furjan, Discovery Gardens</label>
    </customValue>
    <customValue>
        <fullName>Meydan</fullName>
    </customValue>
    <customValue>
        <fullName>Andermatt</fullName>
    </customValue>
    <customValue>
        <fullName>Al Marjan Island - RAK</fullName>
    </customValue>
    <customValue>
        <fullName>TBILISI</fullName>
    </customValue>
    <masterLabel>District</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MSAzureAiTriggerHandlerTest.cls
@isTest
private class MSAzureAiTriggerHandlerTest { 
    @isTest
    static void testAccount() {
        Account acc = new Account();
        acc.Name = 'Test';
        acc.BillingCity = 'Paris';
        insert acc;

        acc.Name = 'Test New';
        acc.BillingCity = 'New York';
        update acc;
    }

    @isTest
    static void testContact() {
        Account acc = new Account();
        acc.Name = 'Test';
        insert acc;
        Contact c = new Contact();
        c.AccountId = acc.Id;
        c.LastName = 'Test';
        insert c;

        c.LastName = 'Test New';
        update c;
    }

    @isTest
    static void testProject() {
        Project__c prj = new Project__c (
            Name = 'test project', 
            Description__c = 'description', 
            District__c = 'Meydan', 
            Coordinates_Latitude__c = 2, 
            Coordinates_Longitude__c = 1, 
            Handover__c = Date.today(), 
            Minimum_Cost__c = 20
        );

        insert prj;

        prj.Name = 'test project new';
        update prj;
    }
}