force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Booking System Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Invoice_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Reference_Number__c</fullName>
    <label>Invoice Reference Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Only &apos;Published&apos; Units might be booked</errorMessage>
        <filterItems>
            <field>Unit__c.Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Client System Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/N_Genius_Configuration__mdt/N_Genius_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>N-Genius Configuration</label>
    <pluralLabel>N-Genius Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/N_Genius_Configuration__mdt/fields/aedValue__c.field-meta.xml
<CustomField>
    <fullName>aedValue__c</fullName>
    <label>AED Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/N_Genius_Configuration__mdt/fields/Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Reference_Number__c</fullName>
    <label>Reference Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <displayFormat>U-{00000}</displayFormat>
        <label>Unit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prod-backups/2026-08-18-unit-status-wizard/objects/Unit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

prod-backups/2026-08-18-unit-status-wizard/objects/Unit__c/fields/Title_Formula__c.field-meta.xml
<CustomField>
    <fullName>Title_Formula__c</fullName>
    <formula>IF (Title__c=&apos;&apos;,

Type_Formula__c +&apos; &apos;+ Name,

Type_Formula__c +&apos; &apos; + Title__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Title Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PaymentGatewayService.cls
public class PaymentGatewayService {

    public static String requestAccessToken(N_Genius_Configuration__mdt nGeniusConf){
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(nGeniusConf.URL__c + '/identity/auth/access-token?umid=' + nGeniusConf.Reference_Number__c);
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/vnd.ni-identity.v1+json');
        request.setHeader('Accept', 'application/vnd.ni-identity.v1+json');
        request.setBody('');
        request.setHeader('Authorization', 'Basic ' + nGeniusConf.API_Key__c);
        HttpResponse response = http.send(request);
        if(response.getStatusCode() == 200){
            Map<String, Object> results = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
            return (String)results.get('access_token');
        } else {
            return 'Bad request';
        }
    }

    public static String requestCreateInvoice(String accessToken, N_Genius_Configuration__mdt nGeniusConf, Booking__c booking){
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(nGeniusConf.URL__c + '/invoices/outlets/' + nGeniusConf.Reference_Number__c + '/invoice');
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/vnd.ni-invoice.v1+json');
        request.setHeader('Accept', 'application/vnd.ni-invoice.v1+json');
        request.setHeader('Authorization', 'Bearer ' + accessToken);
        Map<String, Object> paymentRequest = new Map<String, Object>();
        paymentRequest.put('firstName', booking.Client__r.First_Name__c);
        paymentRequest.put('lastName', booking.Client__r.Last_Name__c);
        paymentRequest.put('email', booking.Client__r.Email__c);
        paymentRequest.put('transactionType', 'SALE');
        paymentRequest.put('emailSubject', 'Invoice from M I R A  Developments');
        DateTime now = DateTime.now();
        DateTime tomorrow = now.addDays(1);
        String invoiceExpiryDate = tomorrow.format('yyyy-MM-dd');
        paymentRequest.put('invoiceExpiryDate', invoiceExpiryDate);
        List<Map<String, Object>> items = new List<Map<String, Object>>();
        Map<String, Object> item1 = new Map<String, Object>();
        item1.put('description', booking.Unit__r.Project__r.Name + ' ' + booking.Unit__r.Title_Formula__c + ' Booking');
        Map<String, Object> totalPrice1 = new Map<String, Object>();
        totalPrice1.put('currencyCode', 'AED');
        paymentRequest.put('paymentAttempts', 3);
        totalPrice1.put('value', nGeniusConf.aedValue__c);
        item1.put('totalPrice', totalPrice1);
        item1.put('quantity', 1);
        items.add(item1);

        paymentRequest.put('items', items);
        paymentRequest.put('total', new Map<String, Object>{'currencyCode'=>'AED', 'value'=>nGeniusConf.aedValue__c});
        paymentRequest.put('message', ' ');

        String requestBody = JSON.serialize(paymentRequest);
        request.setBody(requestBody);

        HttpResponse response = http.send(request);
        if(response.getStatusCode() == 201){
            Map<String, Object> jsonResponse = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
            String orderReference = (String)jsonResponse.get('reference');
            return orderReference;
        } else {
            return 'Bad request';
        }
    }

    public static String requestResendInvoice(String accessToken, N_Genius_Configuration__mdt nGeniusConf, Booking__c booking){
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(nGeniusConf.URL__c + '/invoices/outlets/' + nGeniusConf.Reference_Number__c + '/invoice/'+ booking.Invoice_Reference_Number__c +'/resend');
        request.setMethod('PUT');
        request.setHeader('Content-Type', 'application/vnd.ni-invoice.v1+json');
        request.setHeader('Accept', 'application/vnd.ni-invoice.v1+json');
        request.setHeader('Authorization', 'Bearer ' + accessToken);
        Map<String, Object> paymentRequest = new Map<String, Object>();
        paymentRequest.put('email', booking.Client__r.Email__c);
        DateTime now = DateTime.now();
        DateTime tomorrow = now.addDays(1);
        String invoiceExpiryDate = tomorrow.format('yyyy-MM-dd');
        paymentRequest.put('invoiceExpiryDate', invoiceExpiryDate);

        String requestBody = JSON.serialize(paymentRequest);
        request.setBody(requestBody);

        HttpResponse response = http.send(request);
        if(response.getStatusCode() == 200){
            Map<String, Object> jsonResponse = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
            String orderReference = (String)jsonResponse.get('orderReference');
            return orderReference;
        } else {
            return 'Bad request';
        }
    }
}