force-app/main/default/objects/Account/fields/Agency_Registered_Emirate__c.field-meta.xml
<CustomField>
    <fullName>Agency_Registered_Emirate__c</fullName>
    <label>Agency Registered Emirate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Abu Dhabi</fullName>
            </value>
            <value>
                <fullName>Dubai</fullName>
            </value>
            <value>
                <fullName>Sharjah</fullName>
            </value>
            <value>
                <fullName>Ajman</fullName>
            </value>
            <value>
                <fullName>Ras Al Khaimah</fullName>
            </value>
            <value>
                <fullName>Fujairah</fullName>
            </value>
            <value>
                <fullName>Umm Al Quwain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Agency_International__c.field-meta.xml
<CustomField>
    <fullName>Is_Agency_International__c</fullName>
    <label>Is Agency International</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Registration_Number__c</fullName>
    <formula>&quot;REG-&quot; &amp; TEXT(YEAR(DATEVALUE(CreatedDate))) &amp; &quot;-&quot; &amp; LEFT(Id, 5) &amp; &quot;-&quot; &amp;
MID(TEXT(HOUR(TIMEVALUE(CreatedDate))), 1, 2) &amp;
MID(TEXT(MINUTE(TIMEVALUE(CreatedDate))), 1, 2) &amp;
MID(TEXT(SECOND(TIMEVALUE(CreatedDate))), 1, 2)&amp; &quot;-&quot;&amp; TEXT(Serial__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Registration Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete Registration</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Agreement Issued</fullName>
            </value>
            <value>
                <fullName>Half Executed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/VAT_TRN__c.field-meta.xml
<CustomField>
    <fullName>VAT_TRN__c</fullName>
    <label>VAT TRN</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AgencyAccountDetail.cls
global without sharing class AgencyAccountDetail {
    @RemoteAction
    global static String checkAccountStatus(String registrationNumber) {
        // Create a map to store response
        Map<String, Object> responseMap = new Map<String, Object>();

        try {
            // Query the Account based on the registrationNumber
            Account account = [SELECT Id, Name, Status__c, Registration_Number__c, Is_Agency_International__c, VAT_TRN__c, Agency_Registered_Emirate__c FROM Account 
                               WHERE Registration_Number__c = :registrationNumber LIMIT 1];

            responseMap.put('status', 'success');
            responseMap.put('message', 'Account found');
            responseMap.put('data', account); // Add the queried account data
        } catch (Exception e) {
            responseMap.put('status', 'error');
            responseMap.put('message', e.getMessage());
        }

        // Return JSON string
        return JSON.serialize(responseMap);
    }
}