force-app/main/default/objects/Account/fields/Skip_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Skip_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete Registration</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Agreement Issued</fullName>
            </value>
            <value>
                <fullName>Half Executed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <label>Agency</label>
</RecordType>

force-app/main/default/objects/Commission__c/Commission__c.object-meta.xml
<CustomObject>
    <label>Commission</label>
    <nameField>
        <displayFormat>C-{0}</displayFormat>
        <label>Commission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Commission__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Base_Amount__c.field-meta.xml
<CustomField>
    <fullName>Base_Amount__c</fullName>
    <label>Base Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Commission_Amount__c.field-meta.xml
<CustomField>
    <fullName>Commission_Amount__c</fullName>
    <label>Commission Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Commission_Rate__c.field-meta.xml
<CustomField>
    <fullName>Commission_Rate__c</fullName>
    <label>Commission Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Manual_Override__c.field-meta.xml
<CustomField>
    <fullName>Manual_Override__c</fullName>
    <label>Manual Override</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Paid_Amount__c</fullName>
    <label>Paid Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Commission_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Total_Commission_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Commission_Amount__c</fullName>
    <formula>NULLVALUE(Commission_Amount__c, 0) + NULLVALUE(VAT_Amount__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Commission Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Agent.recordType-meta.xml
<RecordType>
    <fullName>Agent</fullName>
    <active>true</active>
    <label>Agent</label>
</RecordType>

tmp-opp-agency/objects/Opportunity/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agency</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Completed</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities Provided</relationshipLabel>
    <relationshipName>Opportunities_Provided</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agency</value>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Agency__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Assisted_by_Agent__c.field-meta.xml
<CustomField>
    <fullName>Assisted_by_Agent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Assisted by Agent?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <displayFormat>U-{00000}</displayFormat>
        <label>Unit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prod-backups/2026-08-18-unit-status-wizard/objects/Unit__c/fields/Commission_Status__c.field-meta.xml
<CustomField>
    <fullName>Commission_Status__c</fullName>
    <label>Commission Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Draft&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <color>#CC0000</color>
                <default>true</default>
                <label>Blocked</label>
            </value>
            <value>
                <fullName>On Approval</fullName>
                <color>#FF0000</color>
                <label>On Approval</label>
            </value>
            <value>
                <fullName>Published</fullName>
                <color>#FF6666</color>
                <label>Available</label>
            </value>
            <value>
                <fullName>Booked</fullName>
                <color>#3333FF</color>
                <label>Booked</label>
            </value>
            <value>
                <fullName>Reserved</fullName>
                <color>#F3D904</color>
                <label>Reserved</label>
            </value>
            <value>
                <fullName>Sold</fullName>
                <color>#419249</color>
                <label>Sold</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Commission_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Eligible</fullName>
    </customValue>
    <customValue>
        <fullName>Invoiced</fullName>
    </customValue>
    <customValue>
        <fullName>Partially Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Fully Paid</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Commission Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UnitCommissionResetTest.cls
@isTest
private class UnitCommissionResetTest {

    private static Id getAccountRecordTypeId() {
        Map<String, Schema.RecordTypeInfo> rtByDevName =
            Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName();
        if (rtByDevName.containsKey('Agency') && rtByDevName.get('Agency').isAvailable()) {
            return rtByDevName.get('Agency').getRecordTypeId();
        }
        for (Schema.RecordTypeInfo info : rtByDevName.values()) {
            if (info.isAvailable() && !info.isMaster()) {
                return info.getRecordTypeId();
            }
        }
        return null;
    }

    private class TestRefs {
        Id agencyId;
        Id oppId;
        Id unitId;
        Id commissionId;
    }

    private static TestRefs createSoldUnitWithCommission() {
        Account agency = new Account(
            Name = 'ResetTest Agency ' + String.valueOf(Crypto.getRandomLong()),
            Company_Email__c = 'resettest_' + String.valueOf(Crypto.getRandomLong()) + '@example.com',
            Status__c = 'Completed',
            Skip_Trigger__c = true
        );
        Id rtId = getAccountRecordTypeId();
        if (rtId != null) agency.RecordTypeId = rtId;
        insert agency;

        Contact agent = new Contact(
            LastName = 'ResetTest Agent ' + String.valueOf(Crypto.getRandomLong()),
            AccountId = agency.Id
        );
        insert agent;

        // Units must be created in the Blocked (Draft) status, then moved to Sold.
        Unit__c unit = new Unit__c(Title__c = 'ResetTest Unit ' + String.valueOf(Crypto.getRandomLong()));
        insert unit;
        update new Unit__c(Id = unit.Id, Status__c = 'Sold');

        Opportunity opp = new Opportunity(
            Name = 'ResetTest Opp ' + String.valueOf(Crypto.getRandomLong()),
            StageName = 'New',
            CloseDate = Date.today().addDays(30),
            AccountId = agency.Id,
            Agency__c = agency.Id,
            Assisted_by_Agent__c = true,
            Agent__c = agent.Id,
            Unit__c = unit.Id,
            Amount = 1000000
        );
        insert opp;

        Commission__c c = new Commission__c(
            Agency__c = agency.Id,
            Opportunity__c = opp.Id,
            Unit__c = unit.Id,
            Base_Amount__c = 1000000,
            Commission_Rate__c = 4
        );
        insert c;

        TestRefs refs = new TestRefs();
        refs.agencyId = agency.Id;
        refs.oppId = opp.Id;
        refs.unitId = unit.Id;
        refs.commissionId = c.Id;
        return refs;
    }

    @isTest
    static void testCancellationClearsUnitStatusAndKeepsCommissionUntouched() {
        TestRefs refs = createSoldUnitWithCommission();

        Unit__c unitBefore = [SELECT Commission_Status__c FROM Unit__c WHERE Id = :refs.unitId];
        System.assertEquals('Unpaid', unitBefore.Commission_Status__c,
            'Commission insert should have marked the unit Unpaid');

        Test.startTest();
        update new Unit__c(Id = refs.unitId, Status__c = 'Draft');
        Test.stopTest();

        Commission__c saved = [SELECT Status__c, Manual_Override__c FROM Commission__c WHERE Id = :refs.commissionId];
        System.assertEquals('Eligible', saved.Status__c,
            'Commission keeps its current status when the unit sale is cancelled');
        System.assertEquals(null, saved.Manual_Override__c,
            'Cancellation must not touch the commission record');

        Unit__c unitAfter = [SELECT Commission_Status__c FROM Unit__c WHERE Id = :refs.unitId];
        System.assertEquals(null, unitAfter.Commission_Status__c,
            'Unit commission status should be cleared so eligibility restarts from scratch');
    }

    @isTest
    static void testCancellationKeepsFullyPaidCommission() {
        TestRefs refs = createSoldUnitWithCommission();

        Commission__c beforePay = [
            SELECT Total_Commission_Amount__c, Commission_Amount__c
            FROM Commission__c
            WHERE Id = :refs.commissionId
        ];
        Decimal fullAmount = (beforePay.Total_Commission_Amount__c != null && beforePay.Total_Commission_Amount__c > 0)
            ? beforePay.Total_Commission_Amount__c
            : beforePay.Commission_Amount__c;
        update new Commission__c(Id = refs.commissionId, Paid_Amount__c = fullAmount);

        Test.startTest();
        update new Unit__c(Id = refs.unitId, Status__c = 'Draft');
        Test.stopTest();

        Commission__c saved = [SELECT Status__c FROM Commission__c WHERE Id = :refs.commissionId];
        System.assertEquals('Fully Paid', saved.Status__c,
            'Fully paid commissions are kept for audit history');

        Unit__c unitAfter = [SELECT Commission_Status__c FROM Unit__c WHERE Id = :refs.unitId];
        System.assertEquals(null, unitAfter.Commission_Status__c,
            'Unit commission status is still cleared so a resale starts a fresh cycle');
    }

    @isTest
    static void testAlreadyCancelledCommissionIsUntouched() {
        TestRefs refs = createSoldUnitWithCommission();
        update new Commission__c(Id = refs.commissionId, Manual_Override__c = 'Cancelled');

        Test.startTest();
        update new Unit__c(Id = refs.unitId, Status__c = 'Draft');
        Test.stopTest();

        Commission__c saved = [SELECT Status__c FROM Commission__c WHERE Id = :refs.commissionId];
        System.assertEquals('Cancelled', saved.Status__c);

        Unit__c unitAfter = [SELECT Commission_Status__c FROM Unit__c WHERE Id = :refs.unitId];
        System.assertEquals(null, unitAfter.Commission_Status__c);
    }

    @isTest
    static void testNonSoldStatusChangeDoesNotTouchCommission() {
        TestRefs refs = createSoldUnitWithCommission();

        Test.startTest();
        // Sold -> Sold with an unrelated field change: nothing should reset.
        update new Unit__c(Id = refs.unitId, Status__c = 'Sold', Description__c = 'Updated');
        Test.stopTest();

        Commission__c saved = [SELECT Status__c FROM Commission__c WHERE Id = :refs.commissionId];
        System.assertEquals('Eligible', saved.Status__c,
            'Commission must stay untouched while the unit remains Sold');

        Unit__c unitAfter = [SELECT Commission_Status__c FROM Unit__c WHERE Id = :refs.unitId];
        System.assertEquals('Unpaid', unitAfter.Commission_Status__c);
    }

    @isTest
    static void testStatusChangeBetweenNonSoldValuesDoesNothing() {
        // Units must be created in the Blocked (Draft) status, then moved elsewhere.
        Unit__c unit = new Unit__c(
            Title__c = 'ResetTest NonSold ' + String.valueOf(Crypto.getRandomLong()),
            Commission_Status__c = 'Unpaid'
        );
        insert unit;
        update new Unit__c(Id = unit.Id, Status__c = 'Published');

        Test.startTest();
        update new Unit__c(Id = unit.Id, Status__c = 'Draft');
        Test.stopTest();

        Unit__c unitAfter = [SELECT Commission_Status__c FROM Unit__c WHERE Id = :unit.Id];
        System.assertEquals('Unpaid', unitAfter.Commission_Status__c,
            'Only a transition away from Sold resets commission tracking');
    }
}