force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete Registration</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Agreement Issued</fullName>
            </value>
            <value>
                <fullName>Half Executed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Trade_License_Number__c.field-meta.xml
<CustomField>
    <fullName>Trade_License_Number__c</fullName>
    <label>Trade License Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AgencyAccountExistsService.cls
@RestResource(urlMapping='/AgencyAccountExist/*')
global with sharing class AgencyAccountExistsService {
	public class AccountDetailsResponse {
        public Account account;
    }
    
    @HttpPost
    global static String getAccountExist(String tradeLicenseNumber) {
        if (String.isBlank(tradeLicenseNumber)) {
            return JSON.serialize('Trade License not provided');
        }
        
        // Query for the account using the account name
        List<Account> accountList = [
            SELECT Id, Name, Trade_License_Number__c, Status__c 
            FROM Account 
            WHERE Trade_License_Number__c = :tradeLicenseNumber 
            LIMIT 1
        ];
        
        if (accountList.isEmpty()) {
            return JSON.serialize('Account Not Found');
        } else {
            return JSON.serialize('Account Exist');
        }
    }
}