force-app/main/default/objects/File__c/File__c.object-meta.xml
<CustomObject>
    <label>File</label>
    <nameField>
        <displayFormat>File-{00000}</displayFormat>
        <label>File Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Files</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/File__c/fields/News__c.field-meta.xml
<CustomField>
    <fullName>News__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>News</label>
    <referenceTo>News__c</referenceTo>
    <relationshipLabel>Files</relationshipLabel>
    <relationshipName>Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/File__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project Preview</fullName>
            </value>
            <value>
                <fullName>Project USP Image</fullName>
            </value>
            <value>
                <fullName>Client Passport Scan</fullName>
            </value>
            <value>
                <fullName>Photos</fullName>
            </value>
            <value>
                <fullName>Schemas/PDFs</fullName>
            </value>
            <value>
                <fullName>News Preview</fullName>
            </value>
            <value>
                <fullName>News Content Photo</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Project Cover Image</fullName>
            </value>
            <value>
                <fullName>Project Map Image</fullName>
            </value>
            <value>
                <fullName>Unit Layout Preview</fullName>
            </value>
            <value>
                <fullName>Project Interior Photos</fullName>
            </value>
            <value>
                <fullName>Project Exterior Photos</fullName>
            </value>
            <value>
                <fullName>Sales Offer</fullName>
            </value>
            <value>
                <fullName>Trade License Scan</fullName>
            </value>
            <value>
                <fullName>Floor Plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/File__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Files</relationshipLabel>
    <relationshipName>Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/News__c/News__c.object-meta.xml
<CustomObject>
    <label>News</label>
    <nameField>
        <label>News Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/News__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <displayFormat>U-{00000}</displayFormat>
        <label>Unit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Draft&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <color>#CC0000</color>
                <default>true</default>
                <label>Blocked</label>
            </value>
            <value>
                <fullName>On Approval</fullName>
                <color>#FF0000</color>
                <label>On Approval</label>
            </value>
            <value>
                <fullName>Published</fullName>
                <color>#FF6666</color>
                <label>Available</label>
            </value>
            <value>
                <fullName>Booked</fullName>
                <color>#3333FF</color>
                <label>Booked</label>
            </value>
            <value>
                <fullName>Reserved</fullName>
                <color>#F3D904</color>
                <label>Reserved</label>
            </value>
            <value>
                <fullName>Sold</fullName>
                <color>#419249</color>
                <label>Sold</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

prod-backups/2026-08-18-unit-status-wizard/objects/Unit__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Real_Estate_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Real_Estate_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Apartment</fullName>
    </customValue>
    <customValue>
        <fullName>Branded Villa</fullName>
    </customValue>
    <customValue>
        <fullName>Townhouse</fullName>
    </customValue>
    <customValue>
        <fullName>Penthouse</fullName>
    </customValue>
    <customValue>
        <fullName>Duplex</fullName>
    </customValue>
    <customValue>
        <fullName>Branded Mansion</fullName>
    </customValue>
    <customValue>
        <fullName>Office</fullName>
    </customValue>
    <customValue>
        <fullName>Retail</fullName>
    </customValue>
    <masterLabel>Real Estate Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/NewsService.cls
@RestResource(urlMapping='/newsService/*')
global without sharing class NewsService {

    @HttpGet
    global static void doGet() {
        RestRequest req = RestContext.request;
        String createdDateFilter = req.params.get('createdDate');
        String unitIdFilter = req.params.get('unitId');
        String limitRowsFilter = req.params.get('limitRows');
        String orderByFilter = req.params.get('orderBy');
        String offsetFilter = req.params.get('offset');
        String dateFilter = req.params.get('date');


        String mainQuery = buildQuery(unitIdFilter, dateFilter, createdDateFilter, orderByFilter, limitRowsFilter, offsetFilter);

        List<News__c> newsList = Database.query(mainQuery);
        System.debug(mainQuery);
        System.debug(newsList);
        Map<Id, List<File__c>> newsIdToPreviewFiles = new Map<Id, List<File__c>>();
        Map<Id, List<File__c>> newsIdToPictureFiles = new Map<Id, List<File__c>>();
        Set<Id> fileIds = new Set<Id>();
        for (News__c news : newsList) {
            if (news.Files__r != null && !news.Files__r.isEmpty()) {
                List<File__c> newsPreviewFiles = new List<File__c>();
                List<File__c> newsPictureFiles = new List<File__c>();

                for(File__c file : news.Files__r){
                    if(file.Type__c == 'News Preview'){
                        newsPreviewFiles.add(file);
                        fileIds.add(file.Id);
                    } else if (file.Type__c == 'News Content Photo'){
                        newsPictureFiles.add(file);
                        fileIds.add(file.Id);
                    }
                }
                newsIdToPreviewFiles.put(news.Id, newsPreviewFiles);
                newsIdToPictureFiles.put(news.Id, newsPictureFiles);
            }
        }

        Map<String,Object> filesMaps = getAttachedFiles(fileIds);

        Map<Id, ContentDocumentLink> fileToContentDocumentLinkMap = (Map<Id, ContentDocumentLink>)filesMaps.get('fileToContentDocumentLinkMap');
        Map<Id, ContentVersion> cdlToContentVersionMap = (Map<Id, ContentVersion>)filesMaps.get('cdlToContentVersionMap');
        Map<Id, ContentDistribution> cvToContentDistributionMap = (Map<Id, ContentDistribution>)filesMaps.get('cvToContentDistributionMap');

        List<Map<String, Object>> responseList = new List<Map<String, Object>>();
        for (News__c news : newsList) {
            if(unitIdFilter != null && newsIdToPreviewFiles.get(news.Id) == null){
                continue;
            } else {
                Map<String, Object> newsMap = new Map<String, Object>();
                newsMap.put('Name', news.Name);
                newsMap.put('Description__c', news.Description__c);
                newsMap.put('CreatedDate', news.CreatedDate);
                newsMap.put('Date', news.Date__c);

                List<String> pictures = new List<String>();
                if (newsIdToPictureFiles.get(news.Id) != null && !newsIdToPictureFiles.get(news.Id).isEmpty()) {
                    for(File__c file : newsIdToPictureFiles.get(news.Id)){
                        if(fileToContentDocumentLinkMap.containsKey(file.Id)){
                            ContentDocumentLink cdl = fileToContentDocumentLinkMap.get(file.Id);
                            if (cdlToContentVersionMap.containsKey(cdl.ContentDocumentId)) {
                                ContentVersion cv = cdlToContentVersionMap.get(cdl.ContentDocumentId);
                                if (cvToContentDistributionMap.containsKey(cv.Id)) {
                                    ContentDistribution cd = cvToContentDistributionMap.get(cv.Id);
                                    pictures.add(cd.ContentDownloadUrl);
                                }
                            }
                        }
                    }
                }
                newsMap.put('Pictures', pictures);

                if (newsIdToPreviewFiles.get(news.Id) != null && !newsIdToPreviewFiles.get(news.Id).isEmpty() && fileToContentDocumentLinkMap.containsKey(newsIdToPreviewFiles.get(news.Id)[0].Id)) {
                    ContentDocumentLink cdl = fileToContentDocumentLinkMap.get(newsIdToPreviewFiles.get(news.Id)[0].Id);
        
                    if (cdlToContentVersionMap.containsKey(cdl.ContentDocumentId)) {
                        ContentVersion cv = cdlToContentVersionMap.get(cdl.ContentDocumentId);
        
                        if (cvToContentDistributionMap.containsKey(cv.Id)) {
                            ContentDistribution cd = cvToContentDistributionMap.get(cv.Id);
                            newsMap.put('News_preview', cd.ContentDownloadUrl);
                        }
                    }
                }
                responseList.add(newsMap);
            }
        }

        RestContext.response.addHeader('Content-Type', 'application/json');
        RestContext.response.responseBody = Blob.valueOf(JSON.serialize(responseList));
    }

    private static Map<String,Object> getAttachedFiles(Set<Id> fileIds){
        Map<String,Object> resultCollections = new Map<String,Object>();
        Map<Id, ContentDocumentLink> fileToContentDocumentLinkMap = new Map<Id, ContentDocumentLink>();
        Map<Id, ContentVersion> cdlToContentVersionMap = new Map<Id, ContentVersion>();
        Map<Id, ContentDistribution> cvToContentDistributionMap = new Map<Id, ContentDistribution>();
        Map<Id, ContentVersion> idToContentVersionMap = new Map<Id, ContentVersion>();
        Set<Id> contentDocumentLinkIds = new Set<Id>();

        if (!fileIds.isEmpty()) {
            List<ContentDocumentLink> cdlList = [SELECT ContentDocumentId, LinkedEntityid FROM ContentDocumentLink WHERE LinkedEntityid IN :fileIds];
            for (ContentDocumentLink cdl : cdlList) {
                fileToContentDocumentLinkMap.put(cdl.LinkedEntityid, cdl);
                contentDocumentLinkIds.add(cdl.ContentDocumentId);
            }
        }



        if (!fileToContentDocumentLinkMap.isEmpty()) {
            List<ContentVersion> cvList = [SELECT ContentDocument.LatestPublishedVersionId, Title, ContentDocumentId FROM ContentVersion WHERE ContentDocumentId IN :contentDocumentLinkIds];
            for (ContentVersion cv : cvList) {
                cdlToContentVersionMap.put(cv.ContentDocumentId, cv);
                idToContentVersionMap.put(cv.Id, cv);
            }
        }

        if (!cdlToContentVersionMap.isEmpty()) {
            List<ContentDistribution> cdList = [SELECT DistributionPublicUrl, ContentDownloadUrl, ContentVersionId FROM ContentDistribution WHERE ContentVersionId IN :idToContentVersionMap.keySet()];
            for (ContentDistribution cd : cdList) {
                cvToContentDistributionMap.put(cd.ContentVersionId, cd);
            }
            List<ContentDistribution> newCds = new List<ContentDistribution>();
            for(Id contentVersionId : idToContentVersionMap.keySet()){
                if(!cvToContentDistributionMap.containsKey(contentVersionId)){
                    ContentDistribution newCd = new ContentDistribution();
                    newCd.Name = idToContentVersionMap.get(contentVersionId).Title;
                    newCd.ContentVersionId = contentVersionId;
                    newCd.PreferencesAllowViewInBrowser = true;
                    newCd.PreferencesNotifyOnVisit = false;
                    newCds.add(newCd);
                }
            }
            insert newCds;
            cdList = [SELECT DistributionPublicUrl, ContentDownloadUrl, ContentVersionId FROM ContentDistribution WHERE ContentVersionId IN :idToContentVersionMap.keySet()];
            for (ContentDistribution cd : cdList) {
                cvToContentDistributionMap.put(cd.ContentVersionId, cd);
            }
        }
        resultCollections.put('fileToContentDocumentLinkMap', fileToContentDocumentLinkMap);
        resultCollections.put('cdlToContentVersionMap', cdlToContentVersionMap);
        resultCollections.put('cvToContentDistributionMap', cvToContentDistributionMap);
        return resultCollections;
    }

    private static String buildQuery(String unitIdFilter, String dateFilter, String createdDateFilter, String orderByFilter, String limitRowsFilter, String offsetFilter){

        String mainQuery = 'SELECT Id, Name, Description__c, CreatedDate, Date__c, '+
        '(SELECT Id, Type__c FROM Files__r WHERE (Type__c = \'News Preview\' OR Type__c = \'News Content Photo\') ';

        if (unitIdFilter != null) {
            mainQuery += ' AND Unit__c = \'' + unitIdFilter + '\'';
        }

        mainQuery += ' ORDER BY CreatedDate ASC) FROM News__c';

        // if(createdDateFilter != null || dateFilter != null){
            mainQuery += ' WHERE Status__c != \'Draft\''; 
        // }

        if (createdDateFilter != null) {
            mainQuery += ' AND CreatedDate ' + createdDateFilter;
        }

        // if(createdDateFilter != null && dateFilter != null){
        //     mainQuery += ' AND '; 
        // }

        if (dateFilter != null) {
            mainQuery += ' AND Date__c ' + dateFilter;
        }

        if (orderByFilter != null) {
            mainQuery += ' ORDER BY ' + orderByFilter;
        }

        if (limitRowsFilter != null) {
            mainQuery += ' LIMIT ' + Integer.valueOf(limitRowsFilter);
        }

        if (offsetFilter != null) {
            mainQuery += ' OFFSET ' + offsetFilter;
        }

        return mainQuery;
    }
}