force-app/main/default/objects/Advantage__c/Advantage__c.object-meta.xml
<CustomObject>
    <label>Advantage</label>
    <nameField>
        <label>Advantage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advantages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Advantage__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Advantages</relationshipLabel>
    <relationshipName>Advantages</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cash_Flow__c/Cash_Flow__c.object-meta.xml
<CustomObject>
    <label>Cash Flow</label>
    <nameField>
        <label>Milestone</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cash Flow</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cash_Flow__c/fields/Cash_Flow_Sum__c.field-meta.xml
<CustomField>
    <fullName>Cash_Flow_Sum__c</fullName>
    <label>Cash Flow Sum</label>
    <referenceTo>Cash_Flow_Sum__c</referenceTo>
    <relationshipLabel>Cash Flow</relationshipLabel>
    <relationshipName>Cash_Flow</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cash_Flow__c/fields/Percent__c.field-meta.xml
<CustomField>
    <fullName>Percent__c</fullName>
    <label>Percent</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Cash_Flow__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(
  OR(
    ISBLANK(Received_Amount__c),
    Received_Amount__c = 0
  ),
  &apos;Pending&apos;,
  IF(
    Received_Amount__c &lt; Price_Formula__c,
    &apos;Partially Paid&apos;,
    &apos;Fully Paid&apos;
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cash_Flow__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Cash Flow</relationshipLabel>
    <relationshipName>Cash_Flow</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cash_Flow_Sum__c/Cash_Flow_Sum__c.object-meta.xml
<CustomObject>
    <label>Cash Flow Sum</label>
    <nameField>
        <label>Cash Flow Sum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cash Flow Sums</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cash_Flow_Sum__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Cash Flow Sums</relationshipLabel>
    <relationshipName>Cash_Flow_Sums</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Favorite__c/Favorite__c.object-meta.xml
<CustomObject>
    <label>Favorite</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Favorite System Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Favorites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Favorite__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Favorites</relationshipLabel>
    <relationshipName>Favorites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/File__c/File__c.object-meta.xml
<CustomObject>
    <label>File</label>
    <nameField>
        <displayFormat>File-{00000}</displayFormat>
        <label>File Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Files</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/File__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Files</relationshipLabel>
    <relationshipName>Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/File__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project Preview</fullName>
            </value>
            <value>
                <fullName>Project USP Image</fullName>
            </value>
            <value>
                <fullName>Client Passport Scan</fullName>
            </value>
            <value>
                <fullName>Photos</fullName>
            </value>
            <value>
                <fullName>Schemas/PDFs</fullName>
            </value>
            <value>
                <fullName>News Preview</fullName>
            </value>
            <value>
                <fullName>News Content Photo</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Project Cover Image</fullName>
            </value>
            <value>
                <fullName>Project Map Image</fullName>
            </value>
            <value>
                <fullName>Unit Layout Preview</fullName>
            </value>
            <value>
                <fullName>Project Interior Photos</fullName>
            </value>
            <value>
                <fullName>Project Exterior Photos</fullName>
            </value>
            <value>
                <fullName>Sales Offer</fullName>
            </value>
            <value>
                <fullName>Trade License Scan</fullName>
            </value>
            <value>
                <fullName>Floor Plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/File__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Files</relationshipLabel>
    <relationshipName>Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Main_Information__c/Main_Information__c.object-meta.xml
<CustomObject>
    <label>Main Information</label>
    <nameField>
        <label>Main Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Main Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Main_Information__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Main Information</relationshipLabel>
    <relationshipName>Main_Information</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Plan__c/Payment_Plan__c.object-meta.xml
<CustomObject>
    <label>Payment Plan</label>
    <nameField>
        <label>Payment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Plan__c/fields/Percent__c.field-meta.xml
<CustomField>
    <fullName>Percent__c</fullName>
    <label>Percent</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Payment_Plan__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Payment Plans</relationshipLabel>
    <relationshipName>Payment_Plans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Coordinates_Latitude__c.field-meta.xml
<CustomField>
    <fullName>Coordinates_Latitude__c</fullName>
    <label>Coordinates/Latitude</label>
    <precision>18</precision>
    <required>true</required>
    <scale>15</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Coordinates_Longitude__c.field-meta.xml
<CustomField>
    <fullName>Coordinates_Longitude__c</fullName>
    <label>Coordinates/Longitude</label>
    <precision>18</precision>
    <required>true</required>
    <scale>15</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>District</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Handover__c.field-meta.xml
<CustomField>
    <fullName>Handover__c</fullName>
    <label>Handover</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Minimum_Cost__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Cost__c</fullName>
    <inlineHelpText>Will be calculated automatically according to all related &apos;Published&apos; Units, after you change their Status or Cost</inlineHelpText>
    <label>Minimum Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <displayFormat>U-{00000}</displayFormat>
        <label>Unit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prod-backups/2026-08-18-unit-status-wizard/objects/Unit__c/fields/Additional_Area__c.field-meta.xml
<CustomField>
    <fullName>Additional_Area__c</fullName>
    <label>Plot Area</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Cost_AED__c.field-meta.xml
<CustomField>
    <fullName>Cost_AED__c</fullName>
    <label>Cost (AED)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Floor</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Living_Space__c.field-meta.xml
<CustomField>
    <fullName>Living_Space__c</fullName>
    <label>Internal BUA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

prod-backups/2026-08-18-unit-status-wizard/objects/Unit__c/fields/Number_of_Bathrooms__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Bathrooms__c</fullName>
    <label>Number of Bathrooms</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Panorama_Link__c.field-meta.xml
<CustomField>
    <fullName>Panorama_Link__c</fullName>
    <label>Panorama (Link)</label>
    <type>Url</type>
</CustomField>

prod-backups/2026-08-18-unit-status-wizard/objects/Unit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Total_Area__c.field-meta.xml
<CustomField>
    <fullName>Total_Area__c</fullName>
    <label>Total BUA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

prod-backups/2026-08-18-unit-status-wizard/objects/Unit__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Real_Estate_Type</valueSetName>
    </valueSet>
</CustomField>

prod-backups/2026-08-18-unit-status-wizard/objects/Unit__c/fields/View__c.field-meta.xml
<CustomField>
    <fullName>View__c</fullName>
    <label>View</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/District.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Discovery Gardens</fullName>
        <default>true</default>
        <label>Al Furjan, Discovery Gardens</label>
    </customValue>
    <customValue>
        <fullName>Meydan</fullName>
    </customValue>
    <customValue>
        <fullName>Andermatt</fullName>
    </customValue>
    <customValue>
        <fullName>Al Marjan Island - RAK</fullName>
    </customValue>
    <customValue>
        <fullName>TBILISI</fullName>
    </customValue>
    <masterLabel>District</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Real_Estate_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Apartment</fullName>
    </customValue>
    <customValue>
        <fullName>Branded Villa</fullName>
    </customValue>
    <customValue>
        <fullName>Townhouse</fullName>
    </customValue>
    <customValue>
        <fullName>Penthouse</fullName>
    </customValue>
    <customValue>
        <fullName>Duplex</fullName>
    </customValue>
    <customValue>
        <fullName>Branded Mansion</fullName>
    </customValue>
    <customValue>
        <fullName>Office</fullName>
    </customValue>
    <customValue>
        <fullName>Retail</fullName>
    </customValue>
    <masterLabel>Real Estate Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProjectUnitDetailsServiceTest.cls
@isTest
private class ProjectUnitDetailsServiceTest {

    @TestSetup
    static void makeData(){
        
        List<Project__c> projects = new List<Project__c>();
        projects.add(new Project__c (
            Name = 'test project', 
            Description__c = 'description', 
            District__c = 'Meydan', 
            Coordinates_Latitude__c = 2, 
            Coordinates_Longitude__c = 1, 
            Handover__c = Date.today(), 
            Minimum_Cost__c = 20
        ));
        insert projects;

        List<Unit__c> units = new List<Unit__c>();

        units.add(new Unit__c(
            Title__c = 'Test Unit',
            Cost_AED__c = 1000000,
            Type__c = 'Apartment',
            Total_Area__c = 1000,
            Living_Space__c = 800,
            Additional_Area__c = 200,
            Floor__c = 5,
            Number_of_Bedrooms__c = 2,
            Number_of_Bathrooms__c = 2,
            View__c = 'Test View',
            Building__c = 'Test Building',
            Panorama_Link__c = 'Test Link',
            Project__c = projects[0].Id
        ));
        units.add(new Unit__c(
            Title__c = 'Test Unit 2',
            Cost_AED__c = 1000000,
            Type__c = 'Apartment',
            Total_Area__c = 1000,
            Living_Space__c = 800,
            Additional_Area__c = 200,
            Floor__c = 5,
            Number_of_Bedrooms__c = 2,
            Number_of_Bathrooms__c = 2,
            View__c = 'Test View',
            Building__c = 'Test Building',
            Panorama_Link__c = 'Test Link',
            Project__c = projects[0].Id
        ));
        insert units;

        List<Cash_Flow_Sum__c> cashFlowSums = new List<Cash_Flow_Sum__c>();

        cashFlowSums.add(new Cash_Flow_Sum__c(
            Unit__c = units[0].Id,
            Name = 'cash Flow test'
        ));

        insert cashFlowSums;

        List<Cash_Flow__c> cashFlows = new List<Cash_Flow__c>();

        cashFlows.add(new Cash_Flow__c(
            Unit__c = units[0].Id,
            Name = 'cash Flow',
            Cash_Flow_Sum__c = cashFlowSums[0].Id,
            Date__c = Date.today()
        ));

        cashFlows.add(new Cash_Flow__c(
            Unit__c = units[0].Id,
            Name = 'cash Flow',
            Cash_Flow_Sum__c = cashFlowSums[0].Id,
            Date__c = Date.today()
        ));

        insert cashFlows;

        List<Payment_Plan__c> paymentPlans = new List<Payment_Plan__c>();

        paymentPlans.add(new Payment_Plan__c(
            Name = 'payment plan',
            Percent__c = 100,
            Date__c = Date.today(),
            Project__c = projects[0].Id
        ));

        insert paymentPlans;


        List<Main_Information__c> mainInformations = new List<Main_Information__c>();

        mainInformations.add(new Main_Information__c(
            Name = 'main info test',
            Description__c = 'desc',
            Project__c = projects[0].Id
        ));

        insert mainInformations;
        List<Advantage__c> advantages = new List<Advantage__c>();

        advantages.add(new Advantage__c(
            Name = 'adv test',
            Description__c = 'desc',
            Project__c = projects[0].Id
        ));

        insert advantages;

        List<File__c> files = new List<File__c>();

        files.add(new File__c(
            Type__c = 'Photos',
            Unit__c = units[0].Id
        ));
        files.add(new File__c(
            Type__c = 'Project Interior Photos',
            Unit__c = units[0].Id
        ));
        files.add(new File__c(
            Type__c = 'Sales Offer',
            Unit__c = units[0].Id
        ));
        files.add(new File__c(
            Type__c = 'Schemas/PDFs',
            Unit__c = units[0].Id
        ));
        files.add(new File__c(
            Type__c = 'Unit Layout Preview',
            Unit__c = units[0].Id
        ));
        files.add(new File__c(
            Type__c = 'Project Interior Photos',
            Project__c = projects[0].Id
        ));
        files.add(new File__c(
            Type__c = 'Unit Layout Preview',
            Unit__c = units[1].Id
        ));
        files.add(new File__c(
            Type__c = 'Photos',
            Unit__c = units[0].Id
        ));
        files.add(new File__c(
            Type__c = 'Project Preview',
            Project__c = projects[0].Id
        ));
        files.add(new File__c(
            Type__c = 'Project Cover Image',
            Project__c = projects[0].Id
        ));
        files.add(new File__c(
            Type__c = 'Project Map Image',
            Project__c = projects[0].Id
        ));
        files.add(new File__c(
            Type__c = 'Project Exterior Photos',
            Project__c = projects[0].Id
        ));
        insert files;

        
        List<ContentVersion> contentVersions = new List<ContentVersion>();
        contentVersions.add(new ContentVersion(
            Title = 'Test Document',
            VersionData = Blob.valueOf('Test content'),
            PathOnClient = 'TestDocument' + '.pdf',
            IsMajorVersion = true
        ));
        contentVersions.add(new ContentVersion(
            Title = 'Test Document2',
            VersionData = Blob.valueOf('Test content'),
            PathOnClient = 'TestDocument' + '.pdf',
            IsMajorVersion = true
        ));
        contentVersions.add(new ContentVersion(
            Title = 'Test Document3',
            VersionData = Blob.valueOf('Test content'),
            PathOnClient = 'TestDocument' + '.pdf',
            IsMajorVersion = true
        ));
        contentVersions.add(new ContentVersion(
            Title = 'Test Document4',
            VersionData = Blob.valueOf('Test content'),
            PathOnClient = 'TestDocument' + '.pdf',
            IsMajorVersion = true
        ));
        contentVersions.add(new ContentVersion(
            Title = 'Test Document5',
            VersionData = Blob.valueOf('Test content'),
            PathOnClient = 'TestDocument' + '.pdf',
            IsMajorVersion = true
        ));
        contentVersions.add(new ContentVersion(
            Title = 'Test Document6',
            VersionData = Blob.valueOf('Test content'),
            PathOnClient = 'TestDocument' + '.pdf',
            IsMajorVersion = true
        ));
        contentVersions.add(new ContentVersion(
            Title = 'Test Document7',
            VersionData = Blob.valueOf('Test content'),
            PathOnClient = 'TestDocument' + '.pdf',
            IsMajorVersion = true
        ));
        contentVersions.add(new ContentVersion(
            Title = 'Test Document8',
            VersionData = Blob.valueOf('Test content'),
            PathOnClient = 'TestDocument' + '.pdf',
            IsMajorVersion = true
        ));
        contentVersions.add(new ContentVersion(
            Title = 'Test Document9',
            VersionData = Blob.valueOf('Test content'),
            PathOnClient = 'TestDocument' + '.pdf',
            IsMajorVersion = true
        ));
        contentVersions.add(new ContentVersion(
            Title = 'Test Document10',
            VersionData = Blob.valueOf('Test content'),
            PathOnClient = 'TestDocument' + '.pdf',
            IsMajorVersion = true
        ));
        contentVersions.add(new ContentVersion(
            Title = 'Test Document11',
            VersionData = Blob.valueOf('Test content'),
            PathOnClient = 'TestDocument' + '.pdf',
            IsMajorVersion = true
        ));
        contentVersions.add(new ContentVersion(
            Title = 'Test Document12',
            VersionData = Blob.valueOf('Test content'),
            PathOnClient = 'TestDocument' + '.pdf',
            IsMajorVersion = true
        ));
        contentVersions.add(new ContentVersion(
            Title = 'Test Document13',
            VersionData = Blob.valueOf('Test content'),
            PathOnClient = 'TestDocument' + '.pdf',
            IsMajorVersion = true
        ));
        insert contentVersions;
        contentVersions = [SELECT Id, ContentDocumentId, Title, FileExtension FROM ContentVersion];

        List<ContentDocumentLink> contentDocumentLinks = new List<ContentDocumentLink>();
        contentDocumentLinks.add(new ContentDocumentLink(
            ContentDocumentId = contentVersions[0].ContentDocumentId,
            LinkedEntityId = files[0].Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        ));
        contentDocumentLinks.add(new ContentDocumentLink(
            ContentDocumentId = contentVersions[1].ContentDocumentId,
            LinkedEntityId = files[1].Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        ));
        contentDocumentLinks.add(new ContentDocumentLink(
            ContentDocumentId = contentVersions[2].ContentDocumentId,
            LinkedEntityId = files[2].Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        ));
        contentDocumentLinks.add(new ContentDocumentLink(
            ContentDocumentId = contentVersions[3].ContentDocumentId,
            LinkedEntityId = files[3].Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        ));
        contentDocumentLinks.add(new ContentDocumentLink(
            ContentDocumentId = contentVersions[4].ContentDocumentId,
            LinkedEntityId = files[4].Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        ));
        contentDocumentLinks.add(new ContentDocumentLink(
            ContentDocumentId = contentVersions[5].ContentDocumentId,
            LinkedEntityId = files[5].Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        ));
        contentDocumentLinks.add(new ContentDocumentLink(
            ContentDocumentId = contentVersions[6].ContentDocumentId,
            LinkedEntityId = files[6].Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        ));
        contentDocumentLinks.add(new ContentDocumentLink(
            ContentDocumentId = contentVersions[7].ContentDocumentId,
            LinkedEntityId = files[7].Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        ));
        contentDocumentLinks.add(new ContentDocumentLink(
            ContentDocumentId = contentVersions[7].ContentDocumentId,
            LinkedEntityId = files[8].Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        ));
        contentDocumentLinks.add(new ContentDocumentLink(
            ContentDocumentId = contentVersions[7].ContentDocumentId,
            LinkedEntityId = files[9].Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        ));
        contentDocumentLinks.add(new ContentDocumentLink(
            ContentDocumentId = contentVersions[7].ContentDocumentId,
            LinkedEntityId = files[10].Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        ));
        contentDocumentLinks.add(new ContentDocumentLink(
            ContentDocumentId = contentVersions[7].ContentDocumentId,
            LinkedEntityId = files[11].Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        ));
        contentDocumentLinks.add(new ContentDocumentLink(
            ContentDocumentId = contentVersions[8].ContentDocumentId,
            LinkedEntityId = advantages[0].Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        ));

        insert contentDocumentLinks;

        units[0].Status__c = 'Published';
        update units;
        projects[0].Publish_Project__c = 'Published';
        projects[0].No_Handover_Payment__c = false;
        update projects;
    }

    @isTest
    static void testDoGet() {
        List<Unit__c> units = [SELECT Id FROM Unit__c ORDER BY Title__c ASC];
        List<Favorite__c> favorites = new List<Favorite__c>();
        favorites.add(new Favorite__c(
            Unit__c = units[0].Id
        ));
        favorites.add(new Favorite__c(
            Unit__c = units[1].Id
        ));
        insert favorites;

        RestRequest req = new RestRequest();
        req.requestURI = '/services/apexrest/projectUnitDetailsService';
        req.httpMethod = 'GET';
        req.params.put('Id', units[0].Id);
        RestResponse response = new RestResponse();

        RestContext.request = req;
        RestContext.response = response;


        Test.startTest();
        ProjectUnitDetailsService.doGet();
        Test.stopTest();

        System.assertEquals('application/json', RestContext.response.headers.get('Content-Type'));
        System.assertNotEquals(null, RestContext.response.responseBody);

        // Map<String, Object> responseBodyMap = (Map<String, Object>)JSON.deserializeUntyped(RestContext.response.responseBody.toString());
        // System.assertEquals(units[0].Id, responseBodyMap.get('id'));
        // System.assertEquals(units[0].Title_Formula__c, responseBodyMap.get('title'));
    }

    @isTest
    static void testDoGet2() {
        List<Unit__c> units = [SELECT Id FROM Unit__c WHERE Title__c = 'Test Unit'];
    
        RestRequest req = new RestRequest();
        req.requestURI = '/services/apexrest/projectUnitDetailsService';
        req.httpMethod = 'GET';
        req.params.put('Id', units[0].Id);
        RestResponse response = new RestResponse();

        RestContext.request = req;
        RestContext.response = response;


        Test.startTest();
        ProjectUnitDetailsService.doGet();
        Test.stopTest();

        System.assertEquals('application/json', RestContext.response.headers.get('Content-Type'));
        System.assertNotEquals(null, RestContext.response.responseBody);

        // Map<String, Object> responseBodyMap = (Map<String, Object>)JSON.deserializeUntyped(RestContext.response.responseBody.toString());
        // System.assertEquals(units[0].Id, responseBodyMap.get('id'));
        // System.assertEquals(units[0].Title_Formula__c, responseBodyMap.get('title'));
    }

}