force-app/main/default/objects/Advantage__c/Advantage__c.object-meta.xml
<CustomObject>
    <label>Advantage</label>
    <nameField>
        <label>Advantage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advantages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Advantage__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Advantages</relationshipLabel>
    <relationshipName>Advantages</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/File__c/File__c.object-meta.xml
<CustomObject>
    <label>File</label>
    <nameField>
        <displayFormat>File-{00000}</displayFormat>
        <label>File Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Files</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/File__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Files</relationshipLabel>
    <relationshipName>Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/File__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project Preview</fullName>
            </value>
            <value>
                <fullName>Project USP Image</fullName>
            </value>
            <value>
                <fullName>Client Passport Scan</fullName>
            </value>
            <value>
                <fullName>Photos</fullName>
            </value>
            <value>
                <fullName>Schemas/PDFs</fullName>
            </value>
            <value>
                <fullName>News Preview</fullName>
            </value>
            <value>
                <fullName>News Content Photo</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Project Cover Image</fullName>
            </value>
            <value>
                <fullName>Project Map Image</fullName>
            </value>
            <value>
                <fullName>Unit Layout Preview</fullName>
            </value>
            <value>
                <fullName>Project Interior Photos</fullName>
            </value>
            <value>
                <fullName>Project Exterior Photos</fullName>
            </value>
            <value>
                <fullName>Sales Offer</fullName>
            </value>
            <value>
                <fullName>Trade License Scan</fullName>
            </value>
            <value>
                <fullName>Floor Plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Coordinates_Latitude__c.field-meta.xml
<CustomField>
    <fullName>Coordinates_Latitude__c</fullName>
    <label>Coordinates/Latitude</label>
    <precision>18</precision>
    <required>true</required>
    <scale>15</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Coordinates_Longitude__c.field-meta.xml
<CustomField>
    <fullName>Coordinates_Longitude__c</fullName>
    <label>Coordinates/Longitude</label>
    <precision>18</precision>
    <required>true</required>
    <scale>15</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>District</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Handover__c.field-meta.xml
<CustomField>
    <fullName>Handover__c</fullName>
    <label>Handover</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Minimum_Cost__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Cost__c</fullName>
    <inlineHelpText>Will be calculated automatically according to all related &apos;Published&apos; Units, after you change their Status or Cost</inlineHelpText>
    <label>Minimum Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/District.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Discovery Gardens</fullName>
        <default>true</default>
        <label>Al Furjan, Discovery Gardens</label>
    </customValue>
    <customValue>
        <fullName>Meydan</fullName>
    </customValue>
    <customValue>
        <fullName>Andermatt</fullName>
    </customValue>
    <customValue>
        <fullName>Al Marjan Island - RAK</fullName>
    </customValue>
    <customValue>
        <fullName>TBILISI</fullName>
    </customValue>
    <masterLabel>District</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContentDocumentLinkTriggerTest.cls
@isTest
private class ContentDocumentLinkTriggerTest {

    @isTest
    static void testContentDocumentLinkTrigger() {
        List<File__c> files = new List<File__c>();
        files.add(new File__c(Type__c = 'Sales Offer'));
        files.add(new File__c(Type__c = 'Unit Layout Preview'));
        insert files;

        List<ContentVersion> cvs = new List<ContentVersion>();
        cvs.add(new ContentVersion(
            Title = 'Test Content',
            PathOnClient = 'test.pdf',
            VersionData = Blob.valueOf('Test Data'),
            IsMajorVersion = true
        ));
        insert cvs;

        ContentDocument cd = [SELECT Id FROM ContentDocument];

        List<ContentDocumentLink> cdls = new List<ContentDocumentLink>();
        cdls.add(new ContentDocumentLink(
            LinkedEntityId = files[0].Id,
            ContentDocumentId = cd.Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        ));
        cdls.add(new ContentDocumentLink(
            LinkedEntityId = files[1].Id,
            ContentDocumentId = cd.Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        ));

        Test.startTest();
        insert cdls;
        Test.stopTest();

        Set<Id> cdlIds = new Set<Id>();
        for(ContentDocumentLink cdl : cdls){
            cdlIds.add(cdl.Id);
        }
        List<ContentDocumentLink> updatedCdls = [SELECT Id, Visibility FROM ContentDocumentLink WHERE Id IN :cdlIds];

        System.assertEquals('AllUsers', updatedCdls[0].Visibility);
        System.assertEquals('AllUsers', updatedCdls[1].Visibility);
    }

    @isTest
    static void testContentDocumentLinkFieldValueNullTrigger() {

        List<Project__c> projects = new List<Project__c>();
        projects.add(new Project__c (
            Name = 'test project', 
            Description__c = 'description', 
            District__c = 'Meydan', 
            Coordinates_Latitude__c = 2, 
            Coordinates_Longitude__c = 1, 
            Handover__c = Date.today(),
            Minimum_Cost__c = 20
        ));
        insert projects;

        List<Advantage__c> advantages = new List<Advantage__c>();
        advantages.add(new Advantage__c(Name = 'Teat Advantage 1', Description__c = 'test', Project__c = projects[0].Id));
        advantages.add(new Advantage__c(Name = 'Teat Advantage 2', Description__c = 'test', Project__c = projects[0].Id));
        insert advantages;

        List<ContentVersion> cvs = new List<ContentVersion>();
        cvs.add(new ContentVersion(
            Title = 'Test Content',
            PathOnClient = 'test.pdf',
            VersionData = Blob.valueOf('Test Data'),
            IsMajorVersion = true
        ));
        insert cvs;

        ContentDocument cd = [SELECT Id FROM ContentDocument];

        List<ContentDocumentLink> cdls = new List<ContentDocumentLink>();
        cdls.add(new ContentDocumentLink(
            LinkedEntityId = advantages[0].Id,
            ContentDocumentId = cd.Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        ));
        cdls.add(new ContentDocumentLink(
            LinkedEntityId = advantages[1].Id,
            ContentDocumentId = cd.Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        ));

        Test.startTest();
        insert cdls;
        Test.stopTest();

        Set<Id> cdlIds = new Set<Id>();
        for(ContentDocumentLink cdl : cdls){
            cdlIds.add(cdl.Id);
        }
        List<ContentDocumentLink> updatedCdls = [SELECT Id, Visibility FROM ContentDocumentLink WHERE Id IN :cdlIds];

        System.assertEquals('AllUsers', updatedCdls[0].Visibility);
        System.assertEquals('AllUsers', updatedCdls[1].Visibility);
    }
}