force-app/main/default/objects/Cash_Flow__c/Cash_Flow__c.object-meta.xml
<CustomObject>
    <label>Cash Flow</label>
    <nameField>
        <label>Milestone</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cash Flow</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cash_Flow__c/fields/Cash_Flow_Sum__c.field-meta.xml
<CustomField>
    <fullName>Cash_Flow_Sum__c</fullName>
    <label>Cash Flow Sum</label>
    <referenceTo>Cash_Flow_Sum__c</referenceTo>
    <relationshipLabel>Cash Flow</relationshipLabel>
    <relationshipName>Cash_Flow</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cash_Flow__c/fields/Installment_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Installment_Milestone__c</fullName>
    <label>Installment</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cash_Flow__c/fields/Percent__c.field-meta.xml
<CustomField>
    <fullName>Percent__c</fullName>
    <label>Percent</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Cash_Flow__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(
  OR(
    ISBLANK(Received_Amount__c),
    Received_Amount__c = 0
  ),
  &apos;Pending&apos;,
  IF(
    Received_Amount__c &lt; Price_Formula__c,
    &apos;Partially Paid&apos;,
    &apos;Fully Paid&apos;
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cash_Flow__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Cash Flow</relationshipLabel>
    <relationshipName>Cash_Flow</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cash_Flow_Sum__c/Cash_Flow_Sum__c.object-meta.xml
<CustomObject>
    <label>Cash Flow Sum</label>
    <nameField>
        <label>Cash Flow Sum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cash Flow Sums</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cash_Flow_Sum__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Cash Flow Sums</relationshipLabel>
    <relationshipName>Cash_Flow_Sums</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Plan__c/Payment_Plan__c.object-meta.xml
<CustomObject>
    <label>Payment Plan</label>
    <nameField>
        <label>Payment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Plan__c/fields/Payment_Plans_Collector__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plans_Collector__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Plans Collector</label>
    <referenceTo>Payment_Plans_Collector__c</referenceTo>
    <relationshipLabel>Payment Plans</relationshipLabel>
    <relationshipName>Payment_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Plan__c/fields/Percent__c.field-meta.xml
<CustomField>
    <fullName>Percent__c</fullName>
    <label>Percent</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Payment_Plan__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Payment Plans</relationshipLabel>
    <relationshipName>Payment_Plans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Plans_Collector__c/Payment_Plans_Collector__c.object-meta.xml
<CustomObject>
    <label>Payment Plans Collector</label>
    <nameField>
        <label>Plan Collector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans Collectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Plans_Collector__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Payment Plans Collectors</relationshipLabel>
    <relationshipName>Payment_Plans_Collectors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Plans_Collector__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <displayFormat>U-{00000}</displayFormat>
        <label>Unit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Payment_Plans_Collector__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plans_Collector__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Plans Collector</label>
    <referenceTo>Payment_Plans_Collector__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

prod-backups/2026-08-18-unit-status-wizard/objects/Unit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Draft&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <color>#CC0000</color>
                <default>true</default>
                <label>Blocked</label>
            </value>
            <value>
                <fullName>On Approval</fullName>
                <color>#FF0000</color>
                <label>On Approval</label>
            </value>
            <value>
                <fullName>Published</fullName>
                <color>#FF6666</color>
                <label>Available</label>
            </value>
            <value>
                <fullName>Booked</fullName>
                <color>#3333FF</color>
                <label>Booked</label>
            </value>
            <value>
                <fullName>Reserved</fullName>
                <color>#F3D904</color>
                <label>Reserved</label>
            </value>
            <value>
                <fullName>Sold</fullName>
                <color>#419249</color>
                <label>Sold</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PlanCollectorTriggerHandler.cls
public class PlanCollectorTriggerHandler {
    private static String getOrdinalSuffix(Integer inputNumber) {
        if (inputNumber >= 11 && inputNumber <= 13) {
            return 'th';
        }
        switch on Math.mod(inputNumber, 10) {
            when 1 {
                return 'st';
            }
            when 2 {
                return 'nd';
            }
            when 3 {
                return 'rd';
            }
            when else {
                return 'th';
            }
        }
    }

    public static void handlePlanCollectorAfterUpdate(List<Payment_Plans_Collector__c> planCollectors, Map<Id,Payment_Plans_Collector__c> oldPlanCollectorMap) {
        List<Payment_Plans_Collector__c> plansToProcess = new List<Payment_Plans_Collector__c>();
        for (Payment_Plans_Collector__c planCollector : planCollectors) {
            if (planCollector.Status__c == 'Published' && oldPlanCollectorMap.get(planCollector.Id).Status__c != 'Published') {
                plansToProcess.add(planCollector);
            }
        }
        
        Map<Id,Unit__c> units = new Map<Id,Unit__c>([SELECT Id, Payment_Plans_Collector__c FROM Unit__c WHERE Payment_Plans_Collector__c IN :plansToProcess AND (Status__c = 'Draft' OR Status__c = 'Published')]);
        List<Cash_Flow_Sum__c> cashFlowSums = [SELECT Id FROM Cash_Flow_Sum__c WHERE Unit__c IN :units.keyset()];
        delete cashFlowSums;
        
        List<Payment_Plan__c> paymentPlans = [SELECT Id, Project__c, Date__c, Name, Percent__c, Payment_Plans_Collector__c FROM Payment_Plan__c WHERE Payment_Plans_Collector__c IN :plansToProcess ORDER BY Date__c ASC];
        Map<Id,Set<String>> projectToYears = new Map<Id,Set<String>>();
        for(Payment_Plan__c paymentPlan : paymentPlans){
            String paymentPlanYear = paymentPlan.Date__c.year().toString();
            if(projectToYears.containsKey(paymentPlan.Payment_Plans_Collector__c)){
                Set<String> years = projectToYears.get(paymentPlan.Payment_Plans_Collector__c);
                years.add(paymentPlanYear);
                projectToYears.put(paymentPlan.Payment_Plans_Collector__c, years);
            } else {
                projectToYears.put(paymentPlan.Payment_Plans_Collector__c, new Set<String>{paymentPlanYear});
            }
        }

        Map<Id,List<Payment_Plan__c>> collectorIdToPaymentPlans = new Map<Id,List<Payment_Plan__c>>();
        for(Payment_Plan__c paymentPlan : paymentPlans){
            if(collectorIdToPaymentPlans.containsKey(paymentPlan.Payment_Plans_Collector__c)){
                List<Payment_Plan__c> collectorPaymentPlans = collectorIdToPaymentPlans.get(paymentPlan.Payment_Plans_Collector__c);
                collectorPaymentPlans.add(paymentPlan);
                collectorIdToPaymentPlans.put(paymentPlan.Payment_Plans_Collector__c, collectorPaymentPlans);
            } else {
                collectorIdToPaymentPlans.put(paymentPlan.Payment_Plans_Collector__c, new List<Payment_Plan__c>{paymentPlan});
            }
        }

        List<Cash_Flow_Sum__c> cashFlowSumsToInsert = new List<Cash_Flow_Sum__c>();
        List<Cash_Flow__c> cashFlowsToInsert = new List<Cash_Flow__c>();
        for(Id unitId : units.keyset()){
            Set<String> years = projectToYears.get(units.get(unitId).Payment_Plans_Collector__c);
            for(String year : years){
                cashFlowSumsToInsert.add(new Cash_Flow_Sum__c(
                    Unit__c = unitId,
                    Name = year
                ));
            }
        }
        insert cashFlowSumsToInsert;

        Map<Id, Map<String,Id>> unitToYearToCashFlowSumMap = new Map<Id, Map<String,Id>>();

        for(Cash_Flow_Sum__c cashFlowSum : cashFlowSumsToInsert){
            if(unitToYearToCashFlowSumMap.containsKey(cashFlowSum.Unit__c)){
                Map<String,Id> yearToCashFlowSum = unitToYearToCashFlowSumMap.get(cashFlowSum.Unit__c);
                yearToCashFlowSum.put(cashFlowSum.Name, cashFlowSum.Id);
                unitToYearToCashFlowSumMap.put(cashFlowSum.Unit__c, yearToCashFlowSum);
            } else {
                unitToYearToCashFlowSumMap.put(cashFlowSum.Unit__c, new Map<String,Id>{cashFlowSum.Name => cashFlowSum.Id});
            }
        }

        for(Id unitId : units.keyset()){
            Id collectorId = units.get(unitId).Payment_Plans_Collector__c;
            Integer installmentCounter = 1;
            for(Payment_Plan__c paymentPlan : collectorIdToPaymentPlans.get(collectorId)){
                String installmentMilestone;
                if(paymentPlan.Name == 'Booking / Reservation') {
                    installmentMilestone = 'Booking / Reservation';
                } else if(paymentPlan.Name == 'Oqood') {
                    installmentMilestone = 'Oqood';
                } else if(paymentPlan.Name == 'DLD Fee') {
                    installmentMilestone = 'DLD Fee';
                } else {
                    installmentMilestone = installmentCounter + getOrdinalSuffix(installmentCounter) + ' Installment';
                    installmentCounter++;
                }
                
                cashFlowsToInsert.add(new Cash_Flow__c(
                    Date__c = paymentPlan.Date__c,
                    Name = paymentPlan.Name,
                    Percent__c = paymentPlan.Percent__c,
                    Unit__c = unitId,
                    Installment_Milestone__c = installmentMilestone,
                    Cash_Flow_Sum__c = unitToYearToCashFlowSumMap.get(unitId).get(paymentPlan.Date__c.year().toString())
                ));
            }
        }

        insert cashFlowsToInsert;
    }
}