force-app/main/default/objects/Cash_Flow__c/Cash_Flow__c.object-meta.xml
<CustomObject>
    <label>Cash Flow</label>
    <nameField>
        <label>Milestone</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cash Flow</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cash_Flow__c/fields/Percent__c.field-meta.xml
<CustomField>
    <fullName>Percent__c</fullName>
    <label>Percent</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Cash_Flow__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Cash Flow</relationshipLabel>
    <relationshipName>Cash_Flow</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Payment_Plan__c/Opportunity_Payment_Plan__c.object-meta.xml
<CustomObject>
    <label>Opportunity Payment Plan</label>
    <nameField>
        <label>Payment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Payment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Payment_Plan__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OpportunityId</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payment Plan</relationshipLabel>
    <relationshipName>Opportunity_Payment_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Payment_Plan__c/fields/Percent__c.field-meta.xml
<CustomField>
    <fullName>Percent__c</fullName>
    <label>Percent</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity_Payment_Plan__c/fields/UnitId__c.field-meta.xml
<CustomField>
    <fullName>UnitId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UnitId</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Payment Plan</relationshipLabel>
    <relationshipName>Unit_Payment_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Plan__c/Payment_Plan__c.object-meta.xml
<CustomObject>
    <label>Payment Plan</label>
    <nameField>
        <label>Payment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Plan__c/fields/Percent__c.field-meta.xml
<CustomField>
    <fullName>Percent__c</fullName>
    <label>Percent</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Payment_Plan__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Payment Plans</relationshipLabel>
    <relationshipName>Payment_Plans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <displayFormat>U-{00000}</displayFormat>
        <label>Unit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prod-backups/2026-08-18-unit-status-wizard/objects/Unit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GenerateOpportunityPaymenPlan.cls
public class GenerateOpportunityPaymenPlan {
    @InvocableMethod(label='Generate Opportunity Payment Plan' description='Generate Opportunity Payment Plan')
    public static void AddPaymentPlan(List<FlowParams> params) {
        List<Payment_Plan__c> payplan = [SELECT Id, Name, Date__c, Percent__c FROM Payment_Plan__c WHERE Project__c = :params[0].ProjectId];
        
        List<Opportunity_Payment_Plan__c> recordsToInsert = new List<Opportunity_Payment_Plan__c>();
        List<Cash_Flow__c> cashFlowToInsert = new List<Cash_Flow__c>();
        
        for (Payment_Plan__c pl: payplan) {
            Opportunity_Payment_Plan__c opplan = new Opportunity_Payment_Plan__c(
                OpportunityId__c = params[0].OpportunityId,
                UnitId__c = params[0].UnitId,
                Name = pl.Name,
                Date__c = pl.Date__c,
                Percent__c = pl.Percent__c
            );
            recordsToInsert.add(opplan);
            
            Cash_Flow__c cf = new Cash_Flow__c(
            	Unit__c = params[0].UnitId,
                Name = pl.Name,
                Date__c = pl.Date__c,
                Percent__c = pl.Percent__c
            );
        }
        insert recordsToInsert;
    }
    
    public class FlowParams {
        @invocableVariable
        public Id ProjectId;
        
        @invocableVariable
        public Id OpportunityId;
        
        @invocableVariable
        public Id UnitId;
    }
}