force-app/main/default/objects/Opportunity/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>IF(
Account.Name &lt;&gt; &apos;&apos;, Account.Name,
Account.FirstName+&quot; &quot;+ Account.MiddleName +&quot; &quot;+Account.LastName
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <formula>Unit__r.Building__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Building</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sold_Date_for_Email__c.field-meta.xml
<CustomField>
    <fullName>Sold_Date_for_Email__c</fullName>
    <formula>TEXT(DAY(DATEVALUE( Sold_Date_Time__c ))) &amp; &apos;-&apos; &amp;
TEXT(MONTH(DATEVALUE( Sold_Date_Time__c ))) &amp; &apos;-&apos; &amp;
TEXT(YEAR(DATEVALUE( Sold_Date_Time__c )))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sold Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <formula>IF(Project_Name__c &lt;&gt; &apos;POST HOTEL &amp; RESIDENCES By ELIE SAAB&apos;, Unit__r.Cost_AED__c, Unit__r.Cost_AED__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit_Title__c.field-meta.xml
<CustomField>
    <fullName>Unit_Title__c</fullName>
    <formula>Unit__r.Title_Formula__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <displayFormat>U-{00000}</displayFormat>
        <label>Unit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

prod-backups/2026-08-18-unit-status-wizard/objects/Unit__c/fields/Project_Name_F__c.field-meta.xml
<CustomField>
    <fullName>Project_Name_F__c</fullName>
    <formula>Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project F</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <formula>IF(Project_Name_F__c = &apos;POST HOTEL &amp; RESIDENCES By ELIE SAAB&apos;, Cost_CHF__c, Cost_AED__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UnitSoldRegistrationNotification.cls
public class UnitSoldRegistrationNotification {
	//Method to send email with PDF attached
    @InvocableMethod
    public static void sendEmailWithPdfAttachment(List<Id> recordIds) {
        //Assuming only one Id is passed from Flow
        Id recordId = recordIds[0];
        //Fetch the recipient email from the record
        Opportunity opp = [SELECT Id, Account_Name__c, Unit__c, Unit_Price__c, Unit_Title__c, Sold_Date_for_Email__c FROM Opportunity WHERE Id = :recordId LIMIT 1];
        Unit__c unt = [SELECT Id, Project_Name_F__c, Building__c FROM Unit__c WHERE Id = :opp.Unit__c LIMIT 1];
        
        //Prepare recipient emails
        List<String> recipientEmails = new List<String>{'admin@bhartirealestateconsultancy.com', 'founder@bhartirealestateconsultancy.com'};
        //List<String> recipientEmails = new List<String>{'sheraz.h@miradevelopments.ae'};
        
        //Set CC Emails
        String ccEmails = 'finance@miradevelopments.ae, jad.orabi@miradevelopments.ae, ayman.a@miradevelopments.ae';
        //String ccEmails = 'sheraz.dev@gmail.com';
        
        //Create an email
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        email.setToAddresses(recipientEmails);
        email.setSubject('Unit ' +opp.Unit_Title__c+ ' is Ready for Registration');
        
        //Set the plain text body
        Decimal unitPrice = opp.Unit_Price__c;
        String formattedAmount = unitPrice.format();
        String emailBody = 'Dear All,\n' +
        'Please note that the below unit is ready to be registered: \n\n'+
        'Customer Name: '+opp.Account_Name__c+'\n'+
        'Unit: '+opp.Unit_Title__c+'\n'+
        'Tower: '+unt.Building__c+'\n'+
        'Project: '+unt.Project_Name_F__c+'\n'+
        'Price: AED '+formattedAmount+'\n'+
        'Sold Date: '+opp.Sold_Date_for_Email__c+'\n\n'+
        'Regards,\n'+
        'Jadallah Orabi \n'+
        'Contracts Management \n\n';
        email.setPlainTextBody(emailBody);
        
        //Add CC addresses if any valid email addresses are present
        if (!String.isBlank(ccEmails)) {
            // Split CC emails by comma and check if any are valid
            List<String> ccList = new List<String>();
            for (String ccEmail : ccEmails.split(',')) {
                ccEmail = ccEmail.trim();
                if (!String.isBlank(ccEmail)) {
                    ccList.add(ccEmail);
                }
            }
            
            //Set CC addresses if we have valid ones
            if (!ccList.isEmpty()) {
                email.setCcAddresses(ccList);
            }
        }
        
        //email.setOrgWideEmailAddressId('0D2U90000000fO9KAI'); //SandBox Organization-Wide Email Address ID for jad.orabi@miradevelopments.ae
        email.setOrgWideEmailAddressId('0D2Rg0000000P85KAE'); //Production Organization-Wide Email Address ID for jad.orabi@miradevelopments.ae
        
        //Send the email
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { email });
    }

    // Custom Exception to handle errors
    public class CustomException extends Exception {}
}