force-app/main/default/objects/Contact/fields/FireBase_Token__c.field-meta.xml
<CustomField>
    <fullName>FireBase_Token__c</fullName>
    <label>Firebase Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <label>Notification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/FireBaseControllerTest.cls
@isTest
private class FireBaseControllerTest {
    
    @isTest
    static void testSendNotifications() {
        Notification__c notification = new Notification__c(
            Name = 'test',
            Description__c = 'Test, test'
        );
        insert notification;
        Contact contact = new Contact(
            LastName = 'test',
            FireBase_token__c = '123'
        );
        insert contact;
        String notificationId = notification.Id;
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        Test.startTest();
        FireBaseController.sendNotifications(notificationId);
        Test.stopTest();
        
    }
    
    private class MockHttpResponseGenerator implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatus('200');
            res.setBody('{"access_token":"dummyAccessToken"}');
            return res;
        }
    }
    
}